name: Deploy and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          npm install 
        working-directory: web
          
      - name: Create .env file
        run: |
          echo "GCP_PROJECT_ID=${GCP_PROJECT_ID}" >> .env
          echo "GCP_KEY_FILE_NAME=${GCP_KEY_FILE_NAME}" >> .env
          echo "GCP_USE_EMULATOR=${GCP_USE_EMULATOR}" >> .env
          echo "DATASTORE_DATASET=${DATASTORE_DATASET}" >> .env
          echo "DATASTORE_EMULATOR_HOST=${DATASTORE_EMULATOR_HOST}" >> .env
          echo "DATASTORE_EMULATOR_HOST_PATH=${DATASTORE_EMULATOR_HOST_PATH}" >> .env
          echo "DATASTORE_HOST=${DATASTORE_HOST}" >> .env
          echo "DATASTORE_PROJECT_ID=${DATASTORE_PROJECT_ID}" >> .env
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_KEY_FILE_NAME: ${{ vars.GCP_KEY_FILE_NAME }}
          GCP_USE_EMULATOR: true
          DATASTORE_DATASET: ${{ secrets.GCP_PROJECT_ID }}
          DATASTORE_EMULATOR_HOST: ${{ vars.DATASTORE_EMULATOR_HOST }}
          DATASTORE_EMULATOR_HOST_PATH: ${{ vars.DATASTORE_EMULATOR_HOST_PATH }}
          DATASTORE_HOST: ${{ vars.DATASTORE_HOST }}
          DATASTORE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        working-directory: web
   
      - name: Install GCP CLI
        run: |
          curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-430.0.0-linux-x86_64.tar.gz
          tar -xf google-cloud-cli-430.0.0-linux-x86_64.tar.gz
          sudo ./google-cloud-sdk/install.sh
      
      - name: Install Java JRE
        run: |
          sudo apt install default-jre
          sudo apt install openjdk-8-jre
    
      - name: Install Java JRE
        run: |
          sudo apt install default-jre
          sudo apt install openjdk-8-jre  

      - name: Configure GCP CLI
        run: |      
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud components install cloud-datastore-emulator
          gcloud beta emulators datastore start --no-store-on-disk --quiet
        working-directory: web

      - name: Start local datastore
        run: |      
          gcloud beta emulators datastore start --no-store-on-disk --quiet
        working-directory: web
   
      - name: Run Mocha tests
        run: |
          npm run test
        working-directory: web
      #- name: Upload a Build Artifact
     #   uses: actions/upload-artifact@v3.1.2
     #   with:
     #     name: revolut
     #     path: ./web
     #     if-no-files-found: error
     #     retention-days: 1
          
  #test:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Install Node.js
  #      uses: actions/setup-node@v2.3.0
  #      with:
  #        node-version: '14.x'
          
  #    - name: Download a Build Artifact
  #      uses: actions/download-artifact@v2.1.1
  #      with:
  #        name: revolut
  #        path: ./

   #   - name: Run Mocha tests
    #    run: npm run test
        
      # - name: Run K6 load tests
      #  run: k6 run loadtests
        
      #- name: Swap blue/green deployment
      #  if: ${{ success() && steps.k6.outputs.overall_result === 'successful' }}
      #  run: |
      #    eb swap development --destination-name production --verbose
