name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
        
      - name: Create Terraform workspace
        run: terraform workspace new pr-${{ github.event.pull_request.number }}
        working-directory: terraform

      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        working-directory: terraform

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform
      
      - name: Terraform plan
        run: terraform plan -out=tf.tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        working-directory: terraform

      - name: Terraform show to convert Terraform plan to text
        run: |
          terraform show -no-color tf.tfplan > ./tf.txt
          echo "terraformPlan=$(cat tf.json | jq -c)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Comment on pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = "${{ github.event.pull_request.number }}";
            const repo = context.repo;
            const comment = `
              Terraform plan has been executed for this pull request.
              - [View Terraform Plan](https://github.com/${repo.owner}/${repo.repo}/pull/${prNumber}/files)
              - [View Terraform Apply](https://github.com/${repo.owner}/${repo.repo}/actions?query=workflow%3A%22Terraform+Workflow%22)
              \`\`\`
              ${terraformPlan}
              \`\`\`
            `;
            github.issues.createComment({
              ...repo,
              issue_number: prNumber,
              body: comment,
            });
